---
- name: ensure nginx packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - nginx

- name: update /etc/nginx/sites-available/{{ nginx_redirect_name }} from template
  template:
    src: etc/nginx/sites-available/redirect
    dest: /etc/nginx/sites-available/{{ nginx_redirect_name }}
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: ensure /etc/nginx/sites-enabled/{{ nginx_redirect_name }} exists and links to ../sites-available/{{ nginx_redirect_name }}
  file:
    path: /etc/nginx/sites-enabled/{{ nginx_redirect_name }}
    src: ../sites-available/{{ nginx_redirect_name }}
    force: yes
    state: link
  notify:
    - restart nginx

- name: ensure that there is not a hostname collision with the nginx default host
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: '^(\s+)(server_name {{ nginx_redirect_hostname }};.*)$'
    backrefs: yes
    line: '\1#\2'
    state: present
  notify:
    - restart nginx

- name: ensure nginx services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nginx
